# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'mud-art'
    sourceRepo: 'test3-k-npm'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'test3'
    includeEnvVars: true

- task: ArtifactoryNpm@2
  inputs:
    command: 'pack and publish'
    artifactoryService: 'mud-art'
    targetRepo: 'test3-k-npm'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'test3'
    includeEnvVars: true

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'mud-art'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'test3'