steps:
- task: NodeTool@0
  inputs:
    versionSpec: "8.x"
  displayName: Install node 8

# install dependencies
- script: npm install
  displayName: npm install

# build
- script: npm run build
  displayName: npm run build

- script: npm run units
  displayName: Run unit tests

# For CI runs on master, automatically publish packages
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'art-gaja'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'art-gaja'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true

- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'art-gaja'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'k-npm'
    status: 'Released'
    sourceRepo: 'k-npm-local'
    includeDependencies: true
    copy: false
    dryRun: false

- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'art-gaja'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true